import {
  app,
  BrowserWindow,
  Menu,
  ipcMain,
  dialog
} from 'electron';

import { autoUpdater } from 'electron-updater';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

let mainWindow = null;

/*
 * ============================================================
 * AUTO UPDATE CONFIGURATION
 * ============================================================
 *
 * GitHub repository is configured in package.json:
 *
 * owner: patelmunaf90
 * repo: charitable-trust-updates
 *
 * electron-updater automatically uses the GitHub Releases
 * configuration generated by electron-builder.
 *
 * DO NOT use setFeedURL() here.
 */

// Do not download updates automatically.
// The user must choose to download the update.
autoUpdater.autoDownload = false;

// Do not automatically install when the application quits.
// User must click "Restart and Install".
autoUpdater.autoInstallOnAppQuit = false;

// Allow downgrade if ever required during testing.
// Can be changed to false for production.
autoUpdater.allowDowngrade = false;


/*
 * ============================================================
 * CREATE MAIN WINDOW
 * ============================================================
 */

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1280,
    height: 800,

    minWidth: 1000,
    minHeight: 600,

    title: "Charitable Trust Accounting (ઑફલાઇન ડેસ્કટોપ એપ્લિકેશન)",

    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,

      preload: path.join(__dirname, 'preload.js'),

      sandbox: true
    }
  });

  /*
   * Load the built Single-File HTML bundle.
   */

  const indexPath = path.join(
    __dirname,
    'dist',
    'index.html'
  );

  mainWindow.loadFile(indexPath).catch((err) => {
    console.error(
      "Failed to load index.html:",
      err
    );
  });

  mainWindow.on('closed', () => {
    mainWindow = null;
  });
}


/*
 * ============================================================
 * APPLICATION MENU
 * ============================================================
 */

const template = [
  {
    label: 'ફાઇલ (File)',

    submenu: [
      {
        label: 'રીલોડ (Reload)',

        accelerator: 'CmdOrCtrl+R',

        click: () => {
          if (mainWindow) {
            mainWindow.reload();
          }
        }
      },

      {
        label: 'ડેવલપર ટૂલ્સ (Developer Tools)',

        accelerator: 'F12',

        click: () => {
          if (mainWindow) {
            mainWindow.webContents.toggleDevTools();
          }
        }
      },

      {
        type: 'separator'
      },

      {
        label: 'બહાર નીકળો (Exit)',
        role: 'quit'
      }
    ]
  },

  {
    label: 'દેખાવ (View)',

    submenu: [
      {
        role: 'resetZoom',
        label: 'રીસેટ ઝૂમ'
      },

      {
        role: 'zoomIn',
        label: 'ઝૂમ ઇન'
      },

      {
        role: 'zoomOut',
        label: 'ઝૂમ આઉટ'
      },

      {
        type: 'separator'
      },

      {
        role: 'togglefullscreen',
        label: 'ફુલ સ્ક્રીન'
      }
    ]
  },

  {
    label: 'મદદ (Help)',

    submenu: [
      {
        label: 'મદદ અને માર્ગદર્શન',

        click: async () => {

          dialog.showMessageBox(
            mainWindow,
            {
              type: 'info',

              title: 'Charitable Trust Accounting',

              message:
                'ટ્રસ્ટ એકાઉન્ટિંગ એપ્લિકેશન (ડેસ્કટોપ વર્ઝન)',

              detail:
                'આ એપ્લિકેશન ઓફલાઇન કામ કરે છે અને તમારો ડેટા તમારા પીસી પર સુરક્ષિત રીતે સાચવે છે.'
            }
          );
        }
      }
    ]
  }
];


/*
 * ============================================================
 * IPC - APPLICATION VERSION
 * ============================================================
 */

ipcMain.handle(
  'get-app-version',
  () => {
    return app.getVersion();
  }
);


/*
 * ============================================================
 * IPC - CHECK FOR UPDATE
 * ============================================================
 */

ipcMain.on(
  'check-for-updates',
  async () => {

    console.log(
      'Checking for application updates...'
    );

    try {

      if (!app.isPackaged) {

        console.log(
          'Update check skipped because application is not packaged.'
        );

        if (mainWindow) {

          mainWindow.webContents.send(
            'update-error',
            'ડેવલપમેન્ટ મોડમાં અપડેટ ચેક કરી શકાતું નથી.'
          );

        }

        return;
      }

      await autoUpdater.checkForUpdates();

    } catch (err) {

      console.error(
        'Manual update check failed:',
        err
      );

      if (mainWindow) {

        mainWindow.webContents.send(
          'update-error',
          err?.message ||
          'અપડેટ સર્વર સાથે કનેક્શન થઈ શક્યું નથી.'
        );

      }
    }
  }
);


/*
 * ============================================================
 * IPC - DOWNLOAD UPDATE
 * ============================================================
 */

ipcMain.on(
  'download-update',
  async () => {

    console.log(
      'Starting update download...'
    );

    try {

      await autoUpdater.downloadUpdate();

    } catch (err) {

      console.error(
        'Update download failed:',
        err
      );

      if (mainWindow) {

        mainWindow.webContents.send(
          'update-error',
          err?.message ||
          'અપડેટ ડાઉનલોડ કરવામાં ખામી આવી છે.'
        );

      }
    }
  }
);


/*
 * ============================================================
 * IPC - INSTALL UPDATE
 * ============================================================
 */

ipcMain.on(
  'install-update',
  () => {

    console.log(
      'Installing downloaded update...'
    );

    /*
     * quitAndInstall will close the application,
     * install the downloaded update,
     * and restart the application.
     */

    autoUpdater.quitAndInstall(
      false,
      true
    );
  }
);


/*
 * ============================================================
 * AUTO UPDATER EVENTS
 * ============================================================
 */


/*
 * Checking for update
 */

autoUpdater.on(
  'checking-for-update',
  () => {

    console.log(
      'Checking for update...'
    );

    if (mainWindow) {

      mainWindow.webContents.send(
        'checking-for-update'
      );
    }
  }
);


/*
 * Update available
 */

autoUpdater.on(
  'update-available',
  (info) => {

    console.log(
      'Update available:',
      info
    );

    if (mainWindow) {

      mainWindow.webContents.send(
        'update-available',
        {
          version: info.version,

          releaseDate: info.releaseDate,

          releaseName: info.releaseName || '',

          releaseNotes: info.releaseNotes || ''
        }
      );
    }
  }
);


/*
 * No update available
 */

autoUpdater.on(
  'update-not-available',
  (info) => {

    console.log(
      'No update available.',
      info
    );

    if (mainWindow) {

      mainWindow.webContents.send(
        'update-not-available',
        {
          version: info?.version || ''
        }
      );
    }
  }
);


/*
 * Download progress
 */

autoUpdater.on(
  'download-progress',
  (progressObj) => {

    console.log(
      `Download progress: ${progressObj.percent}%`
    );

    if (mainWindow) {

      mainWindow.webContents.send(
        'download-progress',
        {
          percent: progressObj.percent,

          transferred:
            progressObj.transferred,

          total:
            progressObj.total,

          bytesPerSecond:
            progressObj.bytesPerSecond,

          delta:
            progressObj.delta
        }
      );
    }
  }
);


/*
 * Update downloaded
 */

autoUpdater.on(
  'update-downloaded',
  (info) => {

    console.log(
      'Update downloaded successfully:',
      info
    );

    if (mainWindow) {

      mainWindow.webContents.send(
        'update-downloaded',
        {
          version: info.version
        }
      );
    }
  }
);


/*
 * Auto updater error
 */

autoUpdater.on(
  'error',
  (err) => {

    console.error(
      'AutoUpdater error:',
      err
    );

    if (mainWindow) {

      mainWindow.webContents.send(
        'update-error',

        err?.message ||
        'અપડેટ પ્રક્રિયા દરમિયાન ક્ષતિ આવી છે.'
      );
    }
  }
);


/*
 * ============================================================
 * APPLICATION READY
 * ============================================================
 */

app.whenReady().then(() => {

  /*
   * Create application menu.
   */

  const menu =
    Menu.buildFromTemplate(template);

  Menu.setApplicationMenu(menu);


  /*
   * Create main window.
   */

  createWindow();


  /*
   * ==========================================================
   * STARTUP UPDATE CHECK
   * ==========================================================
   *
   * Only check when the application is packaged.
   *
   * Development mode will NOT try to contact GitHub.
   */

  if (app.isPackaged) {

    setTimeout(
      async () => {

        console.log(
          'Performing startup update check...'
        );

        try {

          await autoUpdater.checkForUpdates();

        } catch (err) {

          /*
           * If there is no internet or GitHub cannot
           * be reached, simply continue running the app.
           */

          console.warn(
            'Startup update check failed:',
            err?.message
          );

        }

      },
      5000
    );
  }


  /*
   * macOS activation support.
   */

  app.on(
    'activate',
    () => {

      if (
        BrowserWindow.getAllWindows().length === 0
      ) {

        createWindow();

      }
    }
  );
});


/*
 * ============================================================
 * CLOSE APPLICATION
 * ============================================================
 */

app.on(
  'window-all-closed',
  () => {

    if (process.platform !== 'darwin') {

      app.quit();

    }
  }
);